# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 371fbfbcad014242e1248dad80fdfb35f7bd56d8fa57d2eaab8055fa4aa243e355c79c0de12aec3505ae687f5f4bc53d5cd0aa5e0197123bf437c7d007d87945

test:
  secret_key_base: 92fcff90cc4b110683559d4c07c557f3a117701d79363d2d9a401629077aa84ab5511572404622d51ed8d8f1fee5922f9c15f0c6d64feb49f0af7cfe7bc24e0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
